export type { StreamTextResult } from 'ai'

interface AiToolCallPart {
  readonly type: 'tool-call'

  readonly toolName: string

  readonly toolCallId: string

  readonly input: unknown
}

/**
 * Represents a text segment within an AI message.
 */
export interface AiTextPart {
  /**
   * Indicates that this part contains text content.
   */
  readonly type: 'text'

  /**
   * The text content of the message part.
   */
  readonly text: string
}
interface AiTextDeltaPart {
  readonly type: 'text-delta'
  readonly text: string
}

/**
 * Represents an individual component within an AI message, such as text or a tool call.
 */
export type AiMessagePart = AiTextPart | AiToolCallPart

/**
 * Represents an event emitted during an AI stream, potentially containing a text delta or a tool call.
 */
export type AiStreamEvent = AiTextDeltaPart | AiToolCallPart

/**
 * Represents a structured message generated by an AI assistant.
 */
export interface AiAssistantMessage {
  /**
   * The role of the message, which is always 'assistant'.
   */
  readonly role: 'assistant'

  /**
   * The sequence of content parts constituting the message.
   */
  readonly parts: ReadonlyArray<AiMessagePart>

  /**
   * Concatenated text parts.
   */
  readonly text: string
}

/**
 * Defines the reason why an AI generation process has finished.
 */
export type AiFinishReason =
  'completed' | 'max-tokens' | 'tool-call' | 'content-filtered' | 'error' | 'cancelled' | 'unknown'

/**
 * Contains token usage statistics for an AI request, including input, output, and total token counts.
 */
export interface AiUsage {
  /**
   * The number of tokens used for the input.
   */
  readonly inputTokens: number

  /**
   * The number of tokens generated as output.
   */
  readonly outputTokens: number

  /**
   * The optional total number of tokens (input + output).
   */
  readonly totalTokens?: number | undefined
}
