name: coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - run: git fetch origin main

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: pnpm install

      - name: Enable Turbo Remote Cache
        run: |
          echo "TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}" >> $GITHUB_ENV
          echo "TURBO_TEAM=${{ secrets.TURBO_TEAM }}" >> $GITHUB_ENV

      - run: pnpm build

      # ← あなたが作ったやつ
      - run: pnpm coverage:ci:all

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
